export const SET_ALL_COUNTRIES_SUMMARY = "SET_ALL_COUNTRIES_SUMMARY";
export const SET_ALL_COUNTRIES_TIMELINE = "SET_ALL_COUNTRIES_TIMELINE";
export const SET_COUNTRY_SUMMARY = "SET_COUNTRY_SUMMARY";
export const SET_COUNTRY_TIMELINE = "SET_COUNTRY_TIMELINE";
export const SET_PERIOD = "SET_PERIOD";
